services:
  postgres-2:
    image: postgres:13
    restart: always
    container_name: postgres-container
    env_file:
      - ./config/postgres.env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin-container
    env_file:
      - ./config/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres-2

volumes:
  postgres-db-volume:
